version: 2

project_name: zackup

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - id: zackup
    main: .
    binary: zackup
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - freebsd
    goarch:
      - amd64
      - arm64
    mod_timestamp: "{{ .CommitTimestamp }}"

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: digineo
    name: zackup
